<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8ef8c01c-a73b-4683-a69d-a759606fcf18</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymSystem.Domain\GymSystem.Domain.csproj" />
    <ProjectReference Include="..\GymSystem.Infrastructure\GymSystem.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Attachments\Members\" />
    <Folder Include="Attachments\QRCode\" />
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
